baseUrl=https://edu.yesbangladesh.net
loginUrl=https://edu.yesbangladesh.net/login

browser=chrome

adminUsername=admin@yesedu.com
adminPassword=1234

teacherUsername=teacher@yesbangladesh.com
teacherPassword=1234

studentUsername=student@yesbangladesh.com
studentPassword=123456

accountantUsername=accountant@yesbangladesh.com
accountantPassword=1234

implicitWait=10
pageLoadTimeout=30