baseUrl=https://edu.yesbangladesh.net
loginUrl=https://edu.yesbangladesh.net/login

browser=chrome

adminUsername=admin@gmail.com
adminPassword=1234

teacherUsername=ratul@hotmail.com
teacherPassword=123456

studentUsername=abir@hotmail.com
studentPassword=123456

accountantUsername=user_15@infixedu.com
accountantPassword=123456

implicitWait=10
pageLoadTimeout=30